name: aida_app
description: "A Flutter app to record conversations and queries"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  smooth_page_indicator: ^1.2.0+3
  shared_preferences: ^2.3.2
  motion_tab_bar: ^2.0.4
  liquid_progress_indicator: ^0.4.0
  liquid_progress_indicator_v2: ^0.5.0
  simple_ripple_animation: ^0.0.9
  google_fonts: ^6.2.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/IMG_5469.JPG 
    - assets/IMG_5482.PNG 
